### ISSUE TITLE
Exception thrown if Mockito is not a dependency

### ISSUE THREAD

**Issue by jeshan** [przemyslawj/mockito-intellij-plugin#1]
Argument for @NotNull parameter 'aClass' of com/intellij/psi/impl/PsiElementFactoryImpl.createImportStaticStatement must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'aClass' of com/intellij/psi/impl/PsiElementFactoryImpl.createImportStaticStatement must not be null
    at com.intellij.psi.impl.PsiElementFactoryImpl.createImportStaticStatement(PsiElementFactoryImpl.java)
    at org.mockito.plugin.codegen.ImportOrganizer.addStaticImport(ImportOrganizer.java:32)
    at org.mockito.plugin.codegen.StaticImportsInjector.inject(StaticImportsInjector.java:31)
    at org.mockito.plugin.action.GenMockitoActionHandler.executeWriteAction(GenMockitoActionHandler.java:30)
    at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
    at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Issue disappears if I add mockito as a dependency (in Maven pom).
Although not an "issue" as such, I think this exception can be prevented.

**Comment by przemyslawj** [comment]
Crashing the plugin in that situation was definitely a bug, so thank you for reporting this. I modified it so it shows a bit more user friendly message. 

The change should go live once the plugin passes intellij review, should be 1-2 days.

Let me know if you have some other feedback as well!

**Comment by jeshan** [comment]
OK the plugin has been approved and I just tried version 1.2. I confirm that we no longer have the exception but I don't see the message that you were saying. Can you show me a screenshot?

**Comment by przemyslawj** [comment]
Yeah, there was some problem with that message not displaying in reliable way, and I had to change it. Have a look [here](http://snag.gy/6a9Mn.jpg) to see what it should look like. 

Version 1.3 of the plugin will have that fix.
